---
title: "Social Inclusion Analysis"
author: "Yining Hua"
date: "01/27/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(texreg)
library(stargazer)
library(readr)
library(dplyr)
library(ggplot2)
library(mclogit)
```

```{r, message=FALSE, warning=FALSE}
dat <- read_csv("preliminary_data.csv")

col_names <- c("job","marriage", "group","gender","has_local_child",
              "from_rural")
dat[,col_names] <- lapply(dat[,col_names] , factor)

dat$money.left <- dat$income - dat$expence

## Normalize and standardize money left 
dat$money.left <- (dat$money.left - mean(dat$money.left, na.rm = TRUE)) / 
                    sd(dat$money.left, na.rm = TRUE)
dat$participant <- as.character(dat$participant)

dat$migration.scale <- as.factor(dat$migration.scale)
dat$education.group <- as.factor(dat$education)
```

```{r}
head(dat)
```

```{r, warning=FALSE}
# dat$natives_inclusion <- dat$natives.like.me-dat$natives.lookdown.me
dat$city_inclusion <- dat$like.current.city - dat$previous.customs.better +
                      dat$i.am.native + dat$natives.like.me - 
                      dat$natives.lookdown.me
# dat$tendency.livehere <- dat$willing.to.movein + dat$willing.to.stay

dat
```
```{r}
## regroup education
dat$education.group <- NA
dat$education.group[dat$education == "no education"] <- "low"
dat$education.group[dat$education == "primary school"] <- "low"
dat$education.group[dat$education == "midschool"] <- "middle"
dat$education.group[dat$education == "highschool"] <- "middle"
dat$education.group[dat$education =="junior college"] <- "middle"
dat$education.group[dat$education == "college"] <- "high"
dat$education.group[dat$education == "grad"] <- "high"
```

```{r}
## regroup ethnicity 
#dat$ethnicity.group <- "other"
#dat$ethnicity.group[dat$ethnicity == 1] <- "han"
```
```{r, include=FALSE}
library(dplyr)
```

```{r, warning=FALSE}
cbPalette <- c("#e61212", "#ffb300", "#22ff00", "#0015ff", "#00fbff")
d2 <- dat %>% 
  group_by(group, pos_stay) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))

ggplot(d2, aes(x = factor(group), y = perc*100, fill = factor(pos_stay))) +
  geom_bar(stat="identity", width = 0.7) +
  labs(x = "group", y = "percent", fill = "pos_stay") +
  theme_minimal(base_size = 14)
```

```{r, warning=FALSE}
cbPalette <- c("#e61212", "#ffb300", "#22ff00", "#0015ff", "#00fbff")
d2 <- dat %>% 
  group_by(group, pos_stay) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count))

ggplot(d2, aes(x = factor(group), y = perc*100, fill = factor(pos_stay))) +
  geom_bar(stat="identity", width = 0.7) +
  labs(x = "group", y = "percent", fill = "willing.to.stay") +
  theme_minimal(base_size = 14)
```



```{r}
dat$group <- relevel(dat$group, ref = "no group")
dat$job <- relevel(dat$job, ref = "unstable job")
dat$education.group <- relevel(as.factor(dat$education.group), ref = "low")
dat$migration.scale <- relevel(as.factor(dat$migration.scale), 
                                            ref = "intercounty")
dat$age_group <- relevel(as.factor(dat$age_group), ref = "15-22")


```

```{r}
library(broom)

mod1 <- glm(pos_stay ~ group, data=dat)
mod2 <- glm(neg_stay ~ group, data=dat)
```

```{r}
summary(mod1)
```
```{r}
summary(mod2)
```


```{r}
mod3 <- glm(pos_stay ~ group + city_inclusion + money.left + 
            education.group + age_group + marriage + job + has_local_child + 
            gender + migration.scale + housing_type + from_rural + time_stayed, 
              data=dat)
summary(mod3)
```

### We took out the has_local_child co-variate in this model because no one had the variable to be 1 in this group.

```{r}
mod4 <- glm(neg_stay ~ group + city_inclusion + money.left + 
            education.group + age_group + marriage + job + 
            gender + migration.scale + housing_type + from_rural + time_stayed,
              data=dat)
summary(mod4)
```


```{r, include=FALSE}
write_csv(dat,"processed_data.csv")
```

